AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - readme_examples.rb

Metrics/BlockLength:
  AllowedMethods:
    - configure
    - context
    - define
    - describe
    - guard
    - shared_examples

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
